version: '3'

services:
  test:
    image: openjdk:8
    volumes:
      - ${MY_WORKSPACE}:/ws
    working_dir: /ws${WORKSPACE_PATH:-/}
    user: ${MY_USER:-root}
    depends_on:
      - postgres
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SPRING_PROFILES_ACTIVE: test
    command: >
      ./gradlew --no-daemon
      -g ./.gradle-cache
      -Dspring.datasource.url=jdbc:postgresql://postgres:5432/dermoapp
      -Dspring.redis.host=redis
      clean test ktlintCheck jacocoTestReport
  redis:
    image: redis
  postgres:
    image: postgres:13.7
    environment:
      POSTGRES_DB: 'dermoapp'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'