name: CI/CD Pipeline

on:
  push:
    branches: [ feature/IniciarSesion ]
  pull_request:
    branches: [ feature/IniciarSesion ]
  workflow_dispatch:

jobs:
  build:
    environment:
      name: build
    name: Build & Test
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12.6-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: millonarios10
          POSTGRES_DB: forum
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 2s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build & Test with Code Coverage
        run: chmod +x ./gradlew clean build jacocoTestReport jacocoTestCoverageVerification --stacktrace
        env:
          DATABASE_HOST: localhost:5432
          DATABASE_NAME: dermo-diagnostic-db
          DATABASE_USERNAME: postgres
          DATABASE_PASSWORD: millonarios10

      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties
      - name: Publish Code Coverage
        uses: paambaati/codeclimate-action@v2.7.5
        with:
          coverageCommand: chmod +x ./gradlew jacocoFixForCodeClimate
          coverageLocations: ${{github.workspace}}/build/reports/jacoco/test/jacoco.xml:jacoco
          debug: true
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}

      - name: Test Summary
        uses: test-summary/action@v1
        with:
          paths: "build/test-results/test/TEST-*.xml"
        if: always()
